Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.boot_timeout = 600
  config.vm.network "forwarded_port", guest: 9000, host:9000
  config.vm.network "forwarded_port", guest: 3333, host:3333
  config.vm.network "forwarded_port", guest: 3030, host:3030
  config.vm.network "forwarded_port", guest: 8080, host:8080
  config.vm.network "forwarded_port", guest: 5000, host:5000
  config.vm.provider "virtualbox" do |vb|
     vb.name = "OpenRefine"
     vb.memory = "2048"
  end
  shared_dir = "/files"

  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
end
  config.vm.provision "shell", inline: <<-SHELL
    sudo add-apt-repository -y ppa:openjdk-r/ppa
    sudo apt-get update > /dev/null
    sudo apt-get install -y openjdk-8-jre > /dev/null
    echo "JAVA Installed"
    sudo apt-get install -y apache2 > /dev/null
    echo "APACHE Installed"
    cd /vagrant/files/openrefine-2.7-rc.2/ 
    nohup ./refine -i 0.0.0.0 > /dev/null & 
    echo "OpenRefine is running"
    java -jar /vagrant/files/conciliator-2.2.0.jar > /dev/null &
    echo "Conciliator is running"
    sudo apt-get -y install python-pip
    sudo pip install flask
    sudo pip install fuzzywuzzy
    export GEONAMES_USERNAME="workshop_itn"
#   exec bash
    cd /vagrant/files/geonames
    python reconcile.py > /dev/null & 
    echo "Geonames is running"
  SHELL
end